import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const root = path.resolve(__dirname, '..');
const routeFile = path.join(root, 'src', 'routeTree.gen.ts');

const routes = [
  '/',
  '/login',
  '/dashboard',
  '/ternak',
  '/kartu',
  '/posyandu',
  '/kesehatan',
  '/produksi',
  '/pakan',
  '/laporan',
];

const content = `// Generated by scripts/generate-routes.ts
import { createRootRoute, createRoute } from '@tanstack/react-router';
import { Route as RootRoute } from './routes/__root';
import { Route as IndexRoute } from './routes/index';
import { Route as LoginRoute } from './routes/login';
import { Route as DashboardRoute } from './routes/dashboard';
import { Route as TernakRoute } from './routes/ternak';
import { Route as KartuRoute } from './routes/kartu';
import { Route as PosyanduRoute } from './routes/posyandu';
import { Route as KesehatanRoute } from './routes/kesehatan';
import { Route as ProduksiRoute } from './routes/produksi';
import { Route as PakanRoute } from './routes/pakan';
import { Route as LaporanRoute } from './routes/laporan';

const rootRoute = createRootRoute({ component: RootRoute.options.component });

const indexRoute = createRoute({ getParentRoute: () => rootRoute, path: '/', component: IndexRoute.options.component });
const loginRoute = createRoute({ getParentRoute: () => rootRoute, path: '/login', component: LoginRoute.options.component });
const dashboardRoute = createRoute({ getParentRoute: () => rootRoute, path: '/dashboard', component: DashboardRoute.options.component });
const ternakRoute = createRoute({ getParentRoute: () => rootRoute, path: '/ternak', component: TernakRoute.options.component });
const kartuRoute = createRoute({ getParentRoute: () => rootRoute, path: '/kartu', component: KartuRoute.options.component });
const posyanduRoute = createRoute({ getParentRoute: () => rootRoute, path: '/posyandu', component: PosyanduRoute.options.component });
const kesehatanRoute = createRoute({ getParentRoute: () => rootRoute, path: '/kesehatan', component: KesehatanRoute.options.component });
const produksiRoute = createRoute({ getParentRoute: () => rootRoute, path: '/produksi', component: ProduksiRoute.options.component });
const pakanRoute = createRoute({ getParentRoute: () => rootRoute, path: '/pakan', component: PakanRoute.options.component });
const laporanRoute = createRoute({ getParentRoute: () => rootRoute, path: '/laporan', component: LaporanRoute.options.component });

export const routeTree = rootRoute.addChildren([
  indexRoute,
  loginRoute,
  dashboardRoute,
  ternakRoute,
  kartuRoute,
  posyanduRoute,
  kesehatanRoute,
  produksiRoute,
  pakanRoute,
  laporanRoute,
]);
`;

await writeFile(routeFile, content);
console.log('Generated route tree at', routeFile);
