/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TernakRouteImport } from './routes/ternak'
import { Route as ProduksiRouteImport } from './routes/produksi'
import { Route as PakanRouteImport } from './routes/pakan'
import { Route as LaporanRouteImport } from './routes/laporan'
import { Route as KesehatanRouteImport } from './routes/kesehatan'
import { Route as KartuRouteImport } from './routes/kartu'
import { Route as IndexRouteImport } from './routes/index'

const TernakRoute = TernakRouteImport.update({
  id: '/ternak',
  path: '/ternak',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduksiRoute = ProduksiRouteImport.update({
  id: '/produksi',
  path: '/produksi',
  getParentRoute: () => rootRouteImport,
} as any)
const PakanRoute = PakanRouteImport.update({
  id: '/pakan',
  path: '/pakan',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanRoute = LaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => rootRouteImport,
} as any)
const KesehatanRoute = KesehatanRouteImport.update({
  id: '/kesehatan',
  path: '/kesehatan',
  getParentRoute: () => rootRouteImport,
} as any)
const KartuRoute = KartuRouteImport.update({
  id: '/kartu',
  path: '/kartu',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kartu': typeof KartuRoute
  '/kesehatan': typeof KesehatanRoute
  '/laporan': typeof LaporanRoute
  '/pakan': typeof PakanRoute
  '/produksi': typeof ProduksiRoute
  '/ternak': typeof TernakRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kartu': typeof KartuRoute
  '/kesehatan': typeof KesehatanRoute
  '/laporan': typeof LaporanRoute
  '/pakan': typeof PakanRoute
  '/produksi': typeof ProduksiRoute
  '/ternak': typeof TernakRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kartu': typeof KartuRoute
  '/kesehatan': typeof KesehatanRoute
  '/laporan': typeof LaporanRoute
  '/pakan': typeof PakanRoute
  '/produksi': typeof ProduksiRoute
  '/ternak': typeof TernakRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kartu'
    | '/kesehatan'
    | '/laporan'
    | '/pakan'
    | '/produksi'
    | '/ternak'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kartu'
    | '/kesehatan'
    | '/laporan'
    | '/pakan'
    | '/produksi'
    | '/ternak'
  id:
    | '__root__'
    | '/'
    | '/kartu'
    | '/kesehatan'
    | '/laporan'
    | '/pakan'
    | '/produksi'
    | '/ternak'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KartuRoute: typeof KartuRoute
  KesehatanRoute: typeof KesehatanRoute
  LaporanRoute: typeof LaporanRoute
  PakanRoute: typeof PakanRoute
  ProduksiRoute: typeof ProduksiRoute
  TernakRoute: typeof TernakRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ternak': {
      id: '/ternak'
      path: '/ternak'
      fullPath: '/ternak'
      preLoaderRoute: typeof TernakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produksi': {
      id: '/produksi'
      path: '/produksi'
      fullPath: '/produksi'
      preLoaderRoute: typeof ProduksiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pakan': {
      id: '/pakan'
      path: '/pakan'
      fullPath: '/pakan'
      preLoaderRoute: typeof PakanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan': {
      id: '/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof LaporanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kesehatan': {
      id: '/kesehatan'
      path: '/kesehatan'
      fullPath: '/kesehatan'
      preLoaderRoute: typeof KesehatanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kartu': {
      id: '/kartu'
      path: '/kartu'
      fullPath: '/kartu'
      preLoaderRoute: typeof KartuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KartuRoute: KartuRoute,
  KesehatanRoute: KesehatanRoute,
  LaporanRoute: LaporanRoute,
  PakanRoute: PakanRoute,
  ProduksiRoute: ProduksiRoute,
  TernakRoute: TernakRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
