/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as KartuRouteImport } from './routes/kartu'
import { Route as KesehatanRouteImport } from './routes/kesehatan'
import { Route as LaporanRouteImport } from './routes/laporan'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PakanRouteImport } from './routes/pakan'
import { Route as ObatRouteImport } from './routes/obat'
import { Route as PosyanduRouteImport } from './routes/posyandu'
import { Route as ProduksiRouteImport } from './routes/produksi'
import { Route as TernakRouteImport } from './routes/ternak'
import { Route as UsersRouteImport } from './routes/users'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PanduanRouteImport } from './routes/panduan'
import { Route as TernakTambahRouteImport } from './routes/ternak.tambah'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TernakTambahRoute = TernakTambahRouteImport.update({
  id: '/ternak/tambah',
  path: '/ternak/tambah',
  getParentRoute: () => rootRouteImport,
} as any)
const PanduanRoute = PanduanRouteImport.update({
  id: '/panduan',
  path: '/panduan',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const KartuRoute = KartuRouteImport.update({
  id: '/kartu',
  path: '/kartu',
  getParentRoute: () => rootRouteImport,
} as any)
const KesehatanRoute = KesehatanRouteImport.update({
  id: '/kesehatan',
  path: '/kesehatan',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanRoute = LaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PakanRoute = PakanRouteImport.update({
  id: '/pakan',
  path: '/pakan',
  getParentRoute: () => rootRouteImport,
} as any)
const ObatRoute = ObatRouteImport.update({
  id: '/obat',
  path: '/obat',
  getParentRoute: () => rootRouteImport,
} as any)
const PosyanduRoute = PosyanduRouteImport.update({
  id: '/posyandu',
  path: '/posyandu',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduksiRoute = ProduksiRouteImport.update({
  id: '/produksi',
  path: '/produksi',
  getParentRoute: () => rootRouteImport,
} as any)
const TernakRoute = TernakRouteImport.update({
  id: '/ternak',
  path: '/ternak',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/kartu': typeof KartuRoute
  '/kesehatan': typeof KesehatanRoute
  '/laporan': typeof LaporanRoute
  '/login': typeof LoginRoute
  '/pakan': typeof PakanRoute
  '/obat': typeof ObatRoute
  '/posyandu': typeof PosyanduRoute
  '/produksi': typeof ProduksiRoute
  '/ternak': typeof TernakRoute
  '/users': typeof UsersRoute
  '/profile': typeof ProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/kartu': typeof KartuRoute
  '/kesehatan': typeof KesehatanRoute
  '/laporan': typeof LaporanRoute
  '/login': typeof LoginRoute
  '/pakan': typeof PakanRoute
  '/obat': typeof ObatRoute
  '/posyandu': typeof PosyanduRoute
  '/produksi': typeof ProduksiRoute
  '/ternak': typeof TernakRoute
  '/users': typeof UsersRoute
  '/profile': typeof ProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/kartu': typeof KartuRoute
  '/kesehatan': typeof KesehatanRoute
  '/laporan': typeof LaporanRoute
  '/login': typeof LoginRoute
  '/pakan': typeof PakanRoute
  '/obat': typeof ObatRoute
  '/posyandu': typeof PosyanduRoute
  '/produksi': typeof ProduksiRoute
  '/ternak': typeof TernakRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/kartu'
    | '/kesehatan'
    | '/laporan'
    | '/login'
    | '/pakan'
    | '/posyandu'
    | '/produksi'
    | '/ternak'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/kartu'
    | '/kesehatan'
    | '/laporan'
    | '/login'
    | '/pakan'
    | '/posyandu'
    | '/produksi'
    | '/ternak'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/kartu'
    | '/kesehatan'
    | '/laporan'
    | '/login'
    | '/pakan'
    | '/posyandu'
    | '/produksi'
    | '/ternak'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  KartuRoute: typeof KartuRoute
  KesehatanRoute: typeof KesehatanRoute
  LaporanRoute: typeof LaporanRoute
  LoginRoute: typeof LoginRoute
  PakanRoute: typeof PakanRoute
  PosyanduRoute: typeof PosyanduRoute
  ProduksiRoute: typeof ProduksiRoute
  TernakRoute: typeof TernakRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kartu': {
      id: '/kartu'
      path: '/kartu'
      fullPath: '/kartu'
      preLoaderRoute: typeof KartuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kesehatan': {
      id: '/kesehatan'
      path: '/kesehatan'
      fullPath: '/kesehatan'
      preLoaderRoute: typeof KesehatanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan': {
      id: '/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof LaporanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pakan': {
      id: '/pakan'
      path: '/pakan'
      fullPath: '/pakan'
      preLoaderRoute: typeof PakanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obat': {
      id: '/obat'
      path: '/obat'
      fullPath: '/obat'
      preLoaderRoute: typeof ObatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posyandu': {
      id: '/posyandu'
      path: '/posyandu'
      fullPath: '/posyandu'
      preLoaderRoute: typeof PosyanduRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produksi': {
      id: '/produksi'
      path: '/produksi'
      fullPath: '/produksi'
      preLoaderRoute: typeof ProduksiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ternak': {
      id: '/ternak'
      path: '/ternak'
      fullPath: '/ternak'
      preLoaderRoute: typeof TernakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panduan': {
      id: '/panduan'
      path: '/panduan'
      fullPath: '/panduan'
      preLoaderRoute: typeof PanduanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ternak/tambah': {
      id: '/ternak/tambah'
      path: '/ternak/tambah'
      fullPath: '/ternak/tambah'
      preLoaderRoute: typeof TernakTambahRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  KartuRoute: KartuRoute,
  KesehatanRoute: KesehatanRoute,
  LaporanRoute: LaporanRoute,
  LoginRoute: LoginRoute,
  PakanRoute: PakanRoute,
  ObatRoute: ObatRoute,
  PosyanduRoute: PosyanduRoute,
  ProduksiRoute: ProduksiRoute,
  TernakRoute: TernakRoute,
  TernakTambahRoute: TernakTambahRoute,
  UsersRoute: UsersRoute,
  ProfileRoute: ProfileRoute,
  PanduanRoute: PanduanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

